version: "3.9"
services:
  db:
    image: postgres:13.3-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: geouser
      POSTGRES_PASSWORD: geopassword
    restart: always
  geolocation-service:
    container_name: geolocation-service
    image: geolocation:latest
    build: ./geolocation-service
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/geouser
      - SPRING_DATASOURCE_USERNAME=geouser
      - SPRING_DATASOURCE_PASSWORD=geopassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


